# Generated by Django 4.2.5 on 2023-10-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('icfes', models.IntegerField()),
                ('cedula', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('aux_transportation', models.IntegerField(default=0)),
                ('aux_academic', models.IntegerField(default=0)),
                ('beca_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='follow_students.beca')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.IntegerField()),
                ('alimentacion', models.IntegerField()),
                ('academico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dinero', models.FloatField()),
                ('tiempo_acumulado', models.IntegerField()),
                ('tiempo_seleccionado', models.CharField(choices=[('1', 'Dias'), ('2', 'Mes'), ('3', 'Año')], default='1', max_length=2)),
                ('tipo', models.CharField(max_length=20)),
                ('codigo_estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='follow_students.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='major_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='follow_students.major'),
        ),
        migrations.AddField(
            model_name='beca',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_students.donante'),
        ),
        migrations.AddField(
            model_name='beca',
            name='montos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_students.monto'),
        ),
    ]
