# Generated by Django 4.2.5 on 2023-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('grade1', models.FloatField()),
                ('grade2', models.FloatField()),
                ('grade3', models.FloatField()),
            ],
        ),
    ]
