# Generated by Django 4.2.5 on 2023-10-06 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='follow_students.major'),
        ),
    ]
