# Generated by Django 4.2.5 on 2023-10-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
