# Generated by Django 4.2.5 on 2023-10-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('icfes', models.IntegerField()),
                ('cedula', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
