# Generated by Django 4.2.5 on 2023-10-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('icfes', models.IntegerField()),
                ('id_card', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
