# Generated by Django 4.2.5 on 2023-10-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('money_quantity', models.FloatField()),
                ('acumulate_time', models.IntegerField()),
                ('select_time', models.CharField(choices=[('1', 'Dias'), ('2', 'Mes'), ('3', 'Año')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('celphone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('icfes', models.IntegerField()),
                ('cc', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
