# Generated by Django 4.2.6 on 2023-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montos',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
