# Generated by Django 4.2.5 on 2023-10-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_curso_estudiante_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='name',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
