# Generated by Django 4.2.5 on 2023-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('outcome', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_students.student')),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Nota',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='ActividadNoAcademica',
            new_name='NonAcademicActivity',
        ),
        migrations.RenameModel(
            old_name='RegistroActividadEstudiante',
            new_name='RegisNonAcademicActivity',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='curso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='nonacademicactivity',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regisnonacademicactivity',
            old_name='actividad',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='regisnonacademicactivity',
            old_name='dias_asistencia',
            new_name='attendance_days',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
