# Generated by Django 4.2.5 on 2023-10-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_actividadnoacademica_estudiante_registroactividad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroActividad',
            new_name='RegistroActividadEstudiante',
        ),
    ]
