# Generated by Django 4.2.5 on 2023-11-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_quantity', models.FloatField()),
                ('accumulated_time', models.IntegerField()),
                ('selected_time', models.CharField(choices=[('1', 'Dias'), ('2', 'Mes'), ('3', 'Año')], default='1', max_length=2)),
                ('type_mount', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='academico',
            new_name='academic',
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='alimentacion',
            new_name='alimentation',
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='transporte',
            new_name='transport',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='porcentaje_academico',
            new_name='academic_percentage',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='auxilio_transporte',
            new_name='transportation',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(default='favicon_ICESI.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Gasto_beca',
        ),
        migrations.AddField(
            model_name='scholarship_expense',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='follow_students.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarship_expense',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='follow_students.student'),
        ),
    ]
