# Generated by Django 4.2.5 on 2023-09-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_datadp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadp',
            old_name='grade1',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='datadp',
            name='grade2',
        ),
        migrations.RemoveField(
            model_name='datadp',
            name='grade3',
        ),
    ]
