# Generated by Django 4.2.5 on 2023-11-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_initial_data'),
        ('follow_students', '0002_nota_state'),
    ]

    operations = [
    ]
