# Generated by Django 4.2.5 on 2023-11-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipGoalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_students.scholarshipgoal')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_students.scholarship')),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='goals',
            field=models.ManyToManyField(blank=True, through='follow_students.ScholarshipGoalAssociation', to='follow_students.scholarshipgoal'),
        ),
    ]
