# Generated by Django 4.2.5 on 2023-10-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_student_major_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship_expense',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
