# Generated by Django 4.2.5 on 2023-10-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0002_montos_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='auxilio_trasnporte',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='beca',
            name='porcentaje_Academico',
            field=models.IntegerField(default=70),
        ),
    ]
