# Generated by Django 4.2.5 on 2023-10-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_scholarship_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship_expense',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
