# Generated by Django 4.2.5 on 2023-11-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_scholarship_expense_rename_academico_amount_academic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.CharField(default='favicon_ICESI.png', max_length=255),
        ),
    ]
