# Generated by Django 4.2.5 on 2023-10-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_rename_registroactividad_registroactividadestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
