# Generated by Django 4.2.5 on 2023-10-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_scholarship_expense_rename_academico_amount_academic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='transportation_percentage',
            new_name='transportation',
        ),
    ]
