# Generated by Django 4.2.5 on 2023-11-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_consult_rename_curso_course_rename_nota_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regisnonacademicactivity',
            old_name='attendance_days',
            new_name='assistance_days',
        ),
    ]
