# Generated by Django 4.2.5 on 2023-10-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_beca_auxilio_trasnporte_beca_porcentaje_academico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beca',
            old_name='porcentaje_Academico',
            new_name='porcentaje_academico',
        ),
    ]
