# Generated by Django 4.2.5 on 2023-10-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0004_alter_scholarship_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship_expense',
            name='type',
        ),
    ]
