# Generated by Django 4.2.5 on 2023-11-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0004_notification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
    ]
