# Generated by Django 4.2.5 on 2023-10-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0004_rename_porcentaje_academico_beca_porcentaje_academico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beca',
            old_name='auxilio_trasnporte',
            new_name='auxilio_transporte',
        ),
    ]
