# Generated by Django 4.2.5 on 2023-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0004_curso_estudiante_nota_delete_datadp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
