# Generated by Django 4.2.5 on 2023-10-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0005_remove_scholarship_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship_expense',
            name='type',
            field=models.CharField(default='alimentacion', max_length=20),
            preserve_default=False,
        ),
    ]
