# Generated by Django 4.2.5 on 2023-11-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0005_remove_notification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.TextField(default='Notificacion'),
        ),
    ]
