# Generated by Django 4.2.5 on 2023-09-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0005_alter_curso_code_alter_estudiante_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
