# Generated by Django 4.2.5 on 2023-09-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0006_alter_curso_code_alter_estudiante_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
