# Generated by Django 4.2.5 on 2023-10-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0006_scholarship_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aux_academic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='aux_transporte',
            field=models.IntegerField(default=0),
        ),
    ]
