# Generated by Django 4.2.5 on 2023-11-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_scholarshipgoal_scholarshipgoalassociation_and_more'),
        ('follow_students', '0007_notification_state'),
    ]

    operations = [
    ]
