# Generated by Django 4.2.5 on 2023-09-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0008_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
