# Generated by Django 4.2.5 on 2023-11-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_students', '0003_scholarship_expense_rename_academico_amount_academic_and_more'),
        ('follow_students', '0008_merge_20231112_2014'),
    ]

    operations = [
    ]
